title: "Blog"
description: "Blog em Jekyll com tema minima"

url: "https://blog.caroltheastronaut.com"
baseurl: ""
show_excerpts: true
header_pages:
  - index.md
  - blog.md

plugins:
  - jekyll-feed
