title: "Carol the astronaut"
description: "Senior UX/UI Designer"

url: "https://blog.caroltheastronaut.com"
baseurl: ""
show_excerpts: true
header_pages:
  - portfolio.md
titles_from_headings:
  enabled: false

plugins:
  - jekyll-feed
