title: "Carol the astronaut"
description: "Senior UX/UI Designer"

url: "https://blog.caroltheastronaut.com"
baseurl: ""
show_excerpts: true
header_pages:
  - index.md
  - blog.md

plugins:
  - jekyll-feed
